
# 网络代理服务设置，仅支持 HTTP 代理。
networkOptions:
  isEnable: false # 是否启用代理。
  ip: 127.0.0.1   # 代理服务 IP 地址。
  port: 4780      # 代理服务端口号。
  updateUrl: https://api.myzony.com/lrc-tools/update # 更新检查地址。

# 下载器的相关参数配置。
provider:
    # 歌曲标签屏蔽字典替换功能。
    blockWord:
      isEnable: false             # 是否启用屏蔽字典。
      filePath: 'BlockWords.json' # 屏蔽字典的路径。
  # 歌词下载器的相关参数配置。
  lyric:
    # 支持的歌词下载器。
    plugin:
      - name: NetEase   # 基于网易云音乐的歌词下载器。
        priority: 1     # 优先级，升序排列，改为 -1 时禁用。
        depth: 30       # 搜索深度，值越大搜索结果越多，但搜索时间越长。
        additional:
          isEnableRomanOutput: true # 是否启用罗马音输出，本参数仅当对应歌曲有罗马音歌词时有效。
      - name: QQ        # 基于 QQ 音乐的歌词下载器。
        priority: -1
        # depth: 10     # 暂时不支持。
      - name: KuGou     # 基于酷狗音乐的歌词下载器。
        priority: -1
        depth: 10
      - name: KuWo      # 基于酷我音乐的歌词下载器。
        priority: -1
        depth: 10
    # 歌词下载的一些共有配置参数。
    config:
      isOneLine: true                 # 双语歌词是否合并为一行展示。
      lineBreak: "\n"                 # 换行符的类型，记得使用双引号指定。
      isEnableTranslation: true       # 是否启用翻译歌词。
      isOnlyOutputTranslation: false  # 是否只输出翻译歌词。
      isSkipExistLyricFiles: false    # 如果歌词文件已经存在，是否跳过这些文件。
      fileEncoding: 'utf-8'           # 歌词文件的编码格式。
