name: Build

on:
  watch:
    types: [started]

jobs:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
      
    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x


    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
        
    - name: Test Api
      run: |
        cd ./src/ZonyLrcTools.Cli
        dotnet run download
