name: Build

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.x

    - name: Getting Dependence and Building
      run: |
        cd ${{ github.workspace }}/src/ZonyLrcTools.Cli
        dotnet run download -sc netease -o "${{ github.workspace }}/lyric/" -s "${{ secrets.playlist }}" -l

    - name: Archive output
      run: |
        cd ${{ github.workspace }}
        zip -r lyric.zip lyric/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lyric
        path: ${{ github.workspace }}/lyric.zip
