name: Build

on:
  watch:
    types: [started]

jobs:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
      
    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

        
     # Run daily test and redirect output to /dev/null
    - name: Test Api
      run: |
        cd ./src/Ray.BiliBiliTool.Console
        dotnet run 
